### ISSUE TITLE
NWSync GUI v1.2.0 + nwsync 0.3.2

### ISSUE THREAD

**Issue by lord-kryos** [WilliamDraco/nwsync_gui#2]
First, thank you for your work. 
I'm using last versions nwsync (0.3.2) and nwsync gui (1.2.0) and it seems that the command adds two backslash, as you can see in attached image
![image](https://user-images.githubusercontent.com/81738462/113254974-8d32dc80-92c7-11eb-9b2b-3b7188da2eb0.png)

**Comment by WilliamDraco** [comment]
It's an unfortunate consequence of how it captures errors - The real issue is likely that the latest version of nwsync (0.3.2 that you're running) does not ship with all the .dll files that it requires - nwsync_write is therefore crashing due to the missing .dll's.

Recommend that you get the dlls from an older nwsync version and put them into the directory next to nwsync_write.exe - You don't need to downgrade to an older version, just get the dlls out of the old version.

Once you have the necessary dlls, if the error still persists, please let me know.

**Comment by lord-kryos** [comment]
Thank you, now it's running without issues, sorry for the inconveniences

I'm using dll's from version 0.2.5

**Comment by blbdart** [comment]
Hello, I have been having this same exact error as shown above. This is the only post I've ever seen where someone had it. 
I added the dll files from the older version in the exact same way lord-kryos did but it didn't change anything. 
The only difference is mine is nwsyncversion 0.4.3, nim 1.6.0

Any help would be appreciated. Thank you!
